api_base_url: https://api.bifrost.saastack.site
project_id: e70aebe3-8c16-4e12-a705-62c0f89d7e54
project_name: appointy-landing-v2
service_id: dd29a8dd-cfad-4d5c-80d0-0b263a52a877
service_name: landing-web
environment_id: 26797f0d-7ed0-4734-9fc9-8cfd19d949ff
environment_name: production
repository_url: https://github.com/chandrashekhar-appointy/appointy-enterprise-landing.git
default_branch: main
